# Generated by Django 4.0.1 on 2022-03-02 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

# sets up teh models so that data is automatically set into the database 
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # sets up game model
    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_code', models.IntegerField()),
                ('player_num', models.IntegerField()),
                ('game_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('running', models.BooleanField(default=False)),
            ],
        ),
        # sets up player model
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('seeker', models.BooleanField()),
                ('ready', models.BooleanField()),
                ('hider_code', models.CharField(max_length=4, null=True)),
                ('found', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
