# Generated by Django 4.0.2 on 2022-03-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hiding_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='game',
            name='radius',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='game',
            name='seeker_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='seeking_time',
            field=models.IntegerField(default=600),
        ),
    ]
