# Generated by Django 4.0.1 on 2022-03-02 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='player',
            name='hider_code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
