# Generated by Django 4.0.1 on 2022-03-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_game_start_time_player_hider_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hider_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
