# Generated by Django 4.0.1 on 2022-03-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_hider_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
