# Generated by Django 4.0.1 on 2022-03-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_user_profile_alter_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(default='home/zombie.png', max_length=50),
        ),
    ]
