# Generated by Django 4.0.1 on 2022-03-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
