# Generated by Django 4.0.1 on 2022-03-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(default='home/movin_zomb.gif', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
