# Generated by Django 4.0.2 on 2022-03-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
