# Generated by Django 4.0.1 on 2022-03-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_remove_user_profile_user_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(default='home/Human1.png', max_length=100),
        ),
    ]
