# Generated by Django 4.0.2 on 2022-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_alter_user_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(default='home/human1.png', max_length=100),
        ),
    ]
